### ISSUE TITLE
add_package failing on Windows

### ISSUE THREAD

**Issue by rajmohanb** [02strich/pyrpm#10]
I tried to run the add_package() on Windows 10 and notice that it raises RPMError - invalid RPM header. This same command and rpm package works fine on linux.

```
c:\test\pyrpm-master\pyrpm-master>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrpm.tools.createrepo import YumRepository
>>> from pyrpm.yum import YumPackage
>>> repo = YumRepository('dummyrepo')
>>> repo.read()
>>> repo.save()
>>> len(list(repo.packages()))
0
>>> repo.add_package(YumPackage(open('Cython-0.19-3.el7.x86_64.rpm')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyrpm\rpm.py", line 270, in __init__
    self._read_signature()
  File "pyrpm\rpm.py", line 323, in _read_signature
    self.signature = Signature(self.rpmfile)
  File "pyrpm\rpm.py", line 159, in __init__
    raise RPMError('invalid RPM header')
pyrpm.rpm.RPMError: invalid RPM header
>>>
```

Any reason why this should fail on Windows?

**Comment by 02strich** [comment]
No specific reason (I wrote the library to be able to develop on Windows). Does this happen with all RPM packages?

**Comment by rajmohanb** [comment]
I tried with couple of other rpm's and the result is the same. Seems to fail when reading signature.
`class RPM->_read_signature()`

**Comment by rajmohanb** [comment]
The problem was with the way I am handling the file on Windows. I need to specify that this is a binary file. If I call as below, add_package() works fine. 

`repo.add_package(YumPackage(open('Cython-0.19-3.el7.x86_64.rpm', 'rb')))`

**Comment by 02strich** [comment]
Thanks for trying this out. I have updated the overview example to note the 'rb' setting
