### ISSUE TITLE
support for python3?

### ISSUE THREAD

**Issue by rajmohanb** [02strich/pyrpm#11]
Any enhancement plans to support python3? when I try to run with 3.5, I get the StringIO related error.

`ImportError: No module named 'StringIO'`

**Comment by 02strich** [comment]
yeah, I would like to add support for python3. Happy to merge any changes you are making if you continue to work on this before I have time.

**Comment by 02strich** [comment]
Currently I can run the unit tests with Python 3.5.1. Can you confirm whether you have any remaining issues using Python 3?

**Comment by 02strich** [comment]
Please re-open this if you still encounter problems.
