### ISSUE TITLE
'dict' object is not callable: TypeError

### ISSUE THREAD

**Issue by jjustin** [02strich/pyrpm#13]
In python3.6 when calling save method from YumRepository in createrepo.py there seems so be an error including `list` variable.
I have found a solution by changing variable  name to 'listn':
```
    def _create_meta(self, listn, root_tag, local_namespace):
        # create complete document
        tree = ElementTree.ElementTree(ElementTree.Element(root_tag))
        tree.getroot().set('packages', str(len(listn)))
        for pkg_node in list(listn.items()):
            tree.getroot().append(pkg_node[1])
```

**Comment by 02strich** [comment]
Good catch. Can you check out master and see whether this works for you now?

**Comment by jjustin** [comment]
It works
