### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jjustin** [02strich/pyrpm#14]
In createrepo.py on lines 136 and 187 there seems to be a problem with passing string to write into a byte file(or is it stream? i'm new to coding :) )
```
  File "/rpm/pyrpm/tools/createrepo.py", line 136, in save
    file.write("<?xml version='1.0' encoding='utf-8'?>\n")
TypeError: a bytes-like object is required, not 'str'
```
Changing 
```
file.write("<?xml version='1.0' encoding='utf-8'?>\n")
```
to
```
file.write(b"<?xml version='1.0' encoding='utf-8'?>\n")
```
seems to fix the problem.

**Comment by 02strich** [comment]
What version of python are you using?

Sent from my iPhone

On Jul 27, 2017, at 05:57, Janez Justin <notifications@github.com<mailto:notifications@github.com>> wrote:


In createrepo.py on lines 136 and 187 there seems to be a problem with passing string to write into a byte file(or is it stream? i'm new to coding :) )

  File "/rpm/pyrpm/tools/createrepo.py", line 136, in save
    file.write("<?xml version='1.0' encoding='utf-8'?>\n")
TypeError: a bytes-like object is required, not 'str'


Changing

file.write("<?xml version='1.0' encoding='utf-8'?>\n")


to

file.write(b"<?xml version='1.0' encoding='utf-8'?>\n")


seems to fix the problem.

**Comment by jjustin** [comment]
Python3.6 on macOS

**Comment by 02strich** [comment]
Thank you for reporting this. Can you please try master and confirm whether this now works for you?

**Comment by jjustin** [comment]
Line 136 is okay now, but the problems still occurs on line 187

**Comment by 02strich** [comment]
I am sorry about this - somehow my find & fix powers had failed me - please try again with latest master.

**Comment by jjustin** [comment]
Sorry to say, but now there is a closing bracket missing at the end of fixed line

**Comment by 02strich** [comment]
I am truly sorry and this time added a unit test to make sure I am not fat-fingering the next thing. Please try once more.

**Comment by jjustin** [comment]
It works now 👍

**Comment by 02strich** [comment]
Awesome. I just cut v0.5.8 with this and some other minor fixes.
