### ISSUE TITLE
Merging with upstream?

### ISSUE THREAD

**Issue by pombredanne** [02strich/pyrpm#3]
@02strich have you ever considered merging your enhancements back with upstream?

**Comment by 02strich** [comment]
The API of my fork is different from the upstream one and I did not have the time yet to look into making them compatible again. In addition, upstream always seemed to be pretty dead, but seeing pull requests get merged, I might give it a try.

**Comment by 02strich** [comment]
There does not seem to be any activity upstream after the typo fix. Closing this issue for, but please re-open if you have information to indicate upstream becomes alive again.
