### ISSUE TITLE
UnicodeDecodeError with some packages

### ISSUE THREAD

**Issue by krasmussen** [02strich/pyrpm#9]
Example below shows a UnicodeDecodeError being thrown when saving metadata after adding the compat-libcap1-1.10-7.el7.x86_64 package from the Centos 7 repos to a YumRepository.

```
[krasmussen@kras-desktop tmp]$ wget http://mirror.centos.org/centos/7/os/x86_64/Packages/compat-libcap1-1.10-7.el7.x86_64.rpm
--2016-02-10 02:52:26--  http://mirror.centos.org/centos/7/os/x86_64/Packages/compat-libcap1-1.10-7.el7.x86_64.rpm
Resolving mirror.centos.org (mirror.centos.org)... 64.150.179.24
Connecting to mirror.centos.org (mirror.centos.org)|64.150.179.24|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19112 (19K) [application/x-rpm]
Saving to: ‘compat-libcap1-1.10-7.el7.x86_64.rpm’

compat-libcap1-1.10-7.el7.x86_64.rpm                            100%[==========================================================================================================================================>]  18.66K  --.-KB/s   in 0.02s  

2016-02-10 02:52:27 (1.21 MB/s) - ‘compat-libcap1-1.10-7.el7.x86_64.rpm’ saved [19112/19112]

[krasmussen@kras-desktop tmp]$ mkdir -p dummyrepo
[krasmussen@kras-desktop tmp]$ python
Python 2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrpm.tools.createrepo import YumRepository
>>> from pyrpm.yum import YumPackage
>>> repo = YumRepository('dummyrepo')
>>> repo.save()
>>> repo.read()
>>> len(list(repo.packages()))
0
>>> repo.add_package(YumPackage(open('compat-libcap1-1.10-7.el7.x86_64.rpm')))
>>> repo.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyrpm/tools/createrepo.py", line 90, in save
    other_file, other_file_gz = self._create_meta(self.other_data, '{http://linux.duke.edu/metadata/other}otherdata', 'http://linux.duke.edu/metadata/other')
  File "/usr/lib/python2.7/site-packages/pyrpm/tools/createrepo.py", line 181, in _create_meta
    tree.write(file_obj, 'utf-8')
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1090, in _escape_attrib
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 19: ordinal not in range(128)
>>> 
```

**Comment by krasmussen** [comment]
Better format in gist:

https://gist.github.com/krasmussen/26ba7c813ecad97f58b0

**Comment by krasmussen** [comment]
As a hack adding the following seems to bypass the issue:

import sys
reload(sys)
sys.setdefaultencoding('latin-1')

Is there a better way to handle different encoding from within createrepo.py?

**Comment by krasmussen** [comment]
Hack to fix this from within pyrpm/yum.py by dropping changelogs that can't decode to utf-8

[krasmussen@kras-desktop tmp]$ diff /usr/lib/python2.7/site-packages/pyrpm/yum.py /usr/lib/python2.7/site-packages/pyrpm/yum.py.bak
    127,131c127
    <             try:
    <                 ele.append(element('{http://linux.duke.edu/metadata/other}changelog', {'author': changelog.name.decode('utf-8'), 'date': str(changelog.time)}, text=changelog.text.decode('utf-8')))
    <             # Skip on changelog on unicode decode errors
    <             except UnicodeDecodeError:
    <       pass
    ---
    >             ele.append(element('{http://linux.duke.edu/metadata/other}changelog', {'author': changelog.name, 'date': str(changelog.time)}, text=changelog.text))

I'm thinking we should probably attempt to detect the encoding here and convert it to utf-8
Should probably also do this on  the writing of the repodata in createrepo.py.

I might play around with this idea a little and see what I come up with.

**Comment by 02strich** [comment]
Can you please give master a try? I just committed an improvement to fallback to latin-1 if parsing bytes as utf-8 fails.

**Comment by krasmussen** [comment]
Looks good to me.

Thanks.
